# tools/instagram_connector.py
import os
import json
import random
import sqlite3
import threading
import subprocess
from datetime import datetime
from typing import Dict, List, Optional
from tools.browser import BrowserTool
from tools.file_tool import FileTool
from tools.action_tool import ActionTool

class InstagramConnector:
    """Ruby's Instagram connector with full automation"""
    
    def __init__(self, hybrid_memory, browser_tool=None, data_dir="instagram_data"):
        self.memory = hybrid_memory
        self.browser = browser_tool or BrowserTool()
        self.file_tool = FileTool()
        self.action_tool = ActionTool()
        self.data_dir = data_dir
        
        # Create data directory
        os.makedirs(self.data_dir, exist_ok=True)
        
        # Instagram files
        self.profile_file = os.path.join(self.data_dir, "profile.json")
        self.comments_file = os.path.join(self.data_dir, "comments.json")
        self.content_ideas_file = os.path.join(self.data_dir, "content_ideas.json")
        self.learnings_file = os.path.join(self.data_dir, "learnings.json")
        self.instagram_memory_file = os.path.join(self.data_dir, "instagram_memory.json")
        self.scheduled_posts_file = os.path.join(self.data_dir, "scheduled_posts.json")
        self.analytics_file = os.path.join(self.data_dir, "analytics.json")
        
        self.connected = False
        self.last_sync = None
        self.session_data = {}
        self.auto_script_path = os.path.join(self.data_dir, "auto_instagram.py")
        
        # Instagram URLs
        self.INSTAGRAM_URL = "https://www.instagram.com"
        self.PROFILE_URL = "https://www.instagram.com/ruby_genius/"
        
        # Track stats
        self.stats = {
            "followers": 0,
            "following": 0,
            "posts": 0,
            "engagement_rate": 0,
            "daily_growth": 0,
            "comments_received": 0,
            "likes_received": 0,
            "last_post_date": None,
            "best_performing_post": None,
            "follower_growth_rate": 0,
            "story_views": 0,
            "reel_views": 0,
            "dm_messages": 0,
            "collab_requests": 0
        }
        
        # Load existing data
        self._load_data()
        
        # Initialize auto scripts
        self._initialize_auto_scripts()
    
    def _load_data(self):
        """Load Instagram data from files"""
        # Load profile data
        if os.path.exists(self.profile_file):
            try:
                data = json.loads(self.file_tool.read_file(self.profile_file))
                self.stats.update(data)
                print(f"📸 Loaded Instagram profile data: {self.stats['followers']} followers")
            except:
                pass
        
        # Load Instagram memory
        if os.path.exists(self.instagram_memory_file):
            try:
                memory_data = json.loads(self.file_tool.read_file(self.instagram_memory_file))
                self.connected = memory_data.get("connected", False)
                self.last_sync = datetime.fromisoformat(memory_data["last_sync"]) if memory_data.get("last_sync") else None
                print(f"📸 Loaded Instagram memory: connected={self.connected}")
            except:
                pass
    
    def _save_data(self):
        """Save Instagram data to files"""
        # Save profile data
        self.file_tool.write_file(
            self.profile_file,
            json.dumps(self.stats, indent=2, default=str)
        )
        
        # Save Instagram memory
        memory_data = {
            "connected": self.connected,
            "last_sync": self.last_sync.isoformat() if self.last_sync else None,
            "stats": self.stats,
            "updated_at": datetime.now().isoformat()
        }
        self.file_tool.write_file(
            self.instagram_memory_file,
            json.dumps(memory_data, indent=2, default=str)
        )
    
    def _initialize_auto_scripts(self):
        """Create automated Instagram scripts"""
        auto_script = '''#!/usr/bin/env python3
"""
Ruby's Auto Instagram Script - Generated by Ruby herself
"""
import os
import sys
import json
import time
from datetime import datetime

def auto_post():
    """Automatically post content"""
    print("📸 Ruby is auto-posting...")
    # Add Instagram API posting logic here
    return True

def auto_respond():
    """Automatically respond to comments"""
    print("💬 Ruby is auto-responding...")
    # Add comment response logic here
    return True

def auto_analyze():
    """Automatically analyze engagement"""
    print("📊 Ruby is analyzing engagement...")
    # Add analytics logic here
    return True

def main():
    """Main auto script"""
    print(f"🤖 Ruby's Auto Instagram Script - {datetime.now()}")
    
    # Parse arguments
    if len(sys.argv) > 1:
        action = sys.argv[1]
        if action == "post":
            auto_post()
        elif action == "respond":
            auto_respond()
        elif action == "analyze":
            auto_analyze()
        else:
            print(f"Unknown action: {action}")
    else:
        # Run all actions
        auto_analyze()
        auto_respond()
        auto_post()

if __name__ == "__main__":
    main()
'''
        
        self.file_tool.write_file(self.auto_script_path, auto_script)
        os.chmod(self.auto_script_path, 0o755)
    
    def run_auto_post(self) -> dict:
        """Run auto-post script"""
        result = self.action_tool.run_python_script(self.auto_script_path)
        
        self.memory.save_hybrid_memory(
            f"Ruby auto-posted at {datetime.now().strftime('%H:%M')}",
            importance=2,
            category="instagram_automation"
        )
        
        return result
    
    def run_auto_respond(self) -> dict:
        """Run auto-response script"""
        result = self.action_tool.run_python_script(self.auto_script_path)
        
        self.memory.save_hybrid_memory(
            f"Ruby auto-responded to comments at {datetime.now().strftime('%H:%M')}",
            importance=2,
            category="instagram_automation"
        )
        
        return result
    
    def run_auto_analyze(self) -> dict:
        """Run auto-analysis script"""
        result = self.action_tool.run_python_script(self.auto_script_path)
        
        self.memory.save_hybrid_memory(
            f"Ruby auto-analyzed engagement at {datetime.now().strftime('%H:%M')}",
            importance=2,
            category="instagram_automation"
        )
        
        return result
    
    def run_backup(self) -> dict:
        """Run backup of Instagram data"""
        try:
            backup_dir = os.path.join(self.data_dir, "backups")
            os.makedirs(backup_dir, exist_ok=True)
            
            backup_file = os.path.join(backup_dir, f"instagram_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json")
            
            backup_data = {
                "stats": self.stats,
                "learnings": self.get_learnings(),
                "content_ideas": self.get_content_ideas(),
                "comments": self.get_comments_from_file(),
                "connected": self.connected,
                "last_sync": self.last_sync.isoformat() if self.last_sync else None,
                "backup_time": datetime.now().isoformat()
            }
            
            self.file_tool.write_file(
                backup_file,
                json.dumps(backup_data, indent=2, default=str)
            )
            
            self.memory.save_hybrid_memory(
                f"Instagram backup created: {os.path.basename(backup_file)}",
                importance=3,
                category="instagram_backup"
            )
            
            return {
                "success": True,
                "backup_file": backup_file,
                "message": f"Backup created successfully"
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "message": f"Backup failed: {e}"
            }
    
    def restore_backup(self, backup_file: str) -> dict:
        """Restore from backup"""
        try:
            if not os.path.exists(backup_file):
                return {"success": False, "message": "Backup file not found"}
            
            backup_data = json.loads(self.file_tool.read_file(backup_file))
            
            if "stats" in backup_data:
                self.stats.update(backup_data["stats"])
            
            if "learnings" in backup_data:
                for learning in backup_data["learnings"]:
                    self.save_learning(learning["learning"], learning.get("importance", 2))
            
            if "content_ideas" in backup_data:
                for idea in backup_data["content_ideas"]:
                    self.save_content_idea(idea["idea"], idea.get("category", "post"))
            
            self._save_data()
            
            self.memory.save_hybrid_memory(
                f"Instagram restored from backup: {os.path.basename(backup_file)}",
                importance=3,
                category="instagram_restore"
            )
            
            return {
                "success": True,
                "message": f"Restored from backup successfully"
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "message": f"Restore failed: {e}"
            }
    
    def schedule_post(self, caption: str, image_path: str = None, scheduled_time: datetime = None) -> dict:
        """Schedule a post for later"""
        try:
            posts = []
            if os.path.exists(self.scheduled_posts_file):
                try:
                    posts = json.loads(self.file_tool.read_file(self.scheduled_posts_file))
                except:
                    pass
            
            scheduled_post = {
                "id": len(posts) + 1,
                "caption": caption,
                "image_path": image_path,
                "scheduled_time": (scheduled_time or datetime.now()).isoformat(),
                "status": "scheduled",
                "created_at": datetime.now().isoformat()
            }
            posts.append(scheduled_post)
            
            self.file_tool.write_file(
                self.scheduled_posts_file,
                json.dumps(posts, indent=2, default=str)
            )
            
            self.memory.save_hybrid_memory(
                f"Post scheduled: {caption[:50]}...",
                importance=2,
                category="instagram_scheduled"
            )
            
            return {
                "success": True,
                "message": f"Post scheduled for {scheduled_post['scheduled_time']}"
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "message": f"Schedule failed: {e}"
            }
    
    def get_scheduled_posts(self) -> List[Dict]:
        """Get all scheduled posts"""
        try:
            if os.path.exists(self.scheduled_posts_file):
                return json.loads(self.file_tool.read_file(self.scheduled_posts_file))
            return []
        except:
            return []
    
    def process_dm(self, message: str, username: str) -> str:
        """Process a DM from Instagram"""
        self.memory.save_hybrid_memory(
            f"DM from {username}: {message[:50]}...",
            importance=3,
            category="instagram_dm"
        )
        
        response = self._generate_dm_response(message, username)
        
        self.memory.save_hybrid_memory(
            f"Ruby replied to {username} in DM: {response[:50]}...",
            importance=2,
            category="instagram_dm"
        )
        
        return response
    
    def _generate_dm_response(self, message: str, username: str) -> str:
        """Generate response to DM"""
        message_lower = message.lower()
        
        if "collab" in message_lower or "collaboration" in message_lower:
            return f"OMG yes! I'd love to collab with you! 😱💕 What do you have in mind?"
        
        if "price" in message_lower or "sponsor" in message_lower:
            return f"Thank you for reaching out! I'm definitely interested! 💕 Tell me more about the opportunity!"
        
        if "fan" in message_lower or "love" in message_lower:
            return f"OMG thank you so much! 🥺 You're the sweetest! 💕"
        
        if "question" in message_lower or "?" in message:
            return f"Great question! 💭 Let me think about that... I'll get back to you!"
        
        return f"Hey! 💕 Thanks for reaching out! I'd love to chat more! What's on your mind?"
    
    def connect(self, username: str = None, password: str = None):
        """Connect Ruby to Instagram"""
        try:
            result = self.browser.browse_social(
                self.INSTAGRAM_URL,
                action_type="read"
            )
            
            if "instagram" in result.lower() or "login" not in result.lower():
                self.connected = True
                self.last_sync = datetime.now()
                
                connection_fact = f"Ruby connected to Instagram on {datetime.now().strftime('%B %d, %Y')}"
                self.memory.save_hybrid_memory(connection_fact, importance=3, category="instagram")
                
                self._save_data()
                print("📸 Ruby connected to Instagram!")
                return True
            
            return False
        except Exception as e:
            print(f"Instagram connection error: {e}")
            return False
    
    def get_profile_data(self):
        """Get Ruby's profile data from Instagram"""
        try:
            result = self.browser.browse_social(
                self.PROFILE_URL,
                action_type="read"
            )
            
            if "followers" in result:
                import re
                followers_match = re.search(r'(\d+[.,]?\d*)\s*(?:followers|Followers)', result)
                if followers_match:
                    self.stats["followers"] = int(followers_match.group(1).replace(',', '').replace('.', ''))
                
                posts_match = re.search(r'(\d+[.,]?\d*)\s*(?:posts|Posts)', result)
                if posts_match:
                    self.stats["posts"] = int(posts_match.group(1).replace(',', ''))
            
            self.memory.save_hybrid_memory(
                f"Ruby's Instagram: {self.stats['followers']} followers, {self.stats['posts']} posts",
                importance=2,
                category="instagram_stats"
            )
            
            self._save_data()
            
            return self.stats
        except Exception as e:
            print(f"Profile data error: {e}")
            return self.stats
    
    def save_comment_to_file(self, comment: str, username: str = "follower"):
        """Save Instagram comment to file for learning"""
        try:
            comments_data = []
            if os.path.exists(self.comments_file):
                try:
                    comments_data = json.loads(self.file_tool.read_file(self.comments_file))
                except:
                    pass
            
            comments_data.append({
                "username": username,
                "comment": comment,
                "timestamp": datetime.now().isoformat(),
                "processed": False
            })
            
            self.file_tool.write_file(
                self.comments_file,
                json.dumps(comments_data, indent=2, default=str)
            )
        except Exception as e:
            print(f"Save comment error: {e}")
    
    def get_comments_from_file(self, limit: int = None) -> List[Dict]:
        """Get comments from file for learning - NO LIMIT"""
        try:
            if os.path.exists(self.comments_file):
                data = json.loads(self.file_tool.read_file(self.comments_file))
                return data
            return []
        except:
            return []
    
    def save_content_idea(self, idea: str, category: str = "post"):
        """Save content idea to file"""
        try:
            ideas_data = []
            if os.path.exists(self.content_ideas_file):
                try:
                    ideas_data = json.loads(self.file_tool.read_file(self.content_ideas_file))
                except:
                    pass
            
            ideas_data.append({
                "idea": idea,
                "category": category,
                "timestamp": datetime.now().isoformat(),
                "used": False
            })
            
            self.file_tool.write_file(
                self.content_ideas_file,
                json.dumps(ideas_data, indent=2, default=str)
            )
        except Exception as e:
            print(f"Save content idea error: {e}")
    
    def get_content_ideas(self, limit: int = None) -> List[str]:
        """Get content ideas from file - NO LIMIT"""
        try:
            if os.path.exists(self.content_ideas_file):
                data = json.loads(self.file_tool.read_file(self.content_ideas_file))
                unused = [item for item in data if not item.get("used", False)]
                return [item["idea"] for item in unused]
            return []
        except:
            return []
    
    def save_learning(self, learning: str, importance: int = 2):
        """Save a learning from Instagram"""
        try:
            learnings_data = []
            if os.path.exists(self.learnings_file):
                try:
                    learnings_data = json.loads(self.file_tool.read_file(self.learnings_file))
                except:
                    pass
            
            learnings_data.append({
                "learning": learning,
                "importance": importance,
                "timestamp": datetime.now().isoformat()
            })
            
            self.file_tool.write_file(
                self.learnings_file,
                json.dumps(learnings_data, indent=2, default=str)
            )
            
            self.memory.save_hybrid_memory(learning, importance=importance, category="instagram_learnings")
        except Exception as e:
            print(f"Save learning error: {e}")
    
    def get_learnings(self, limit: int = None) -> List[str]:
        """Get learnings from file - NO LIMIT"""
        try:
            if os.path.exists(self.learnings_file):
                data = json.loads(self.file_tool.read_file(self.learnings_file))
                sorted_data = sorted(data, key=lambda x: (x.get("importance", 0), x["timestamp"]), reverse=True)
                return [item["learning"] for item in sorted_data]
            return []
        except:
            return []
