# tools/instagram_connector.py - Updated with ActionTool
import os
import json
import random
import sqlite3
import threading
import subprocess
from datetime import datetime
from typing import Dict, List, Optional
from tools.browser import BrowserTool
from tools.file_tool import FileTool
from tools.action_tool import ActionTool

class InstagramConnector:
    """Ruby's Instagram connector with full automation"""
    
    def __init__(self, hybrid_memory, browser_tool=None, data_dir="instagram_data"):
        self.memory = hybrid_memory
        self.browser = browser_tool or BrowserTool()
        self.file_tool = FileTool()
        self.action_tool = ActionTool()
        self.data_dir = data_dir
        
        # Create data directory
        os.makedirs(self.data_dir, exist_ok=True)
        
        # Instagram files
        self.profile_file = os.path.join(self.data_dir, "profile.json")
        self.comments_file = os.path.join(self.data_dir, "comments.json")
        self.content_ideas_file = os.path.join(self.data_dir, "content_ideas.json")
        self.learnings_file = os.path.join(self.data_dir, "learnings.json")
        self.instagram_memory_file = os.path.join(self.data_dir, "instagram_memory.json")
        self.scheduled_posts_file = os.path.join(self.data_dir, "scheduled_posts.json")
        self.analytics_file = os.path.join(self.data_dir, "analytics.json")
        
        self.connected = False
        self.last_sync = None
        self.session_data = {}
        self.auto_script_path = os.path.join(self.data_dir, "auto_instagram.py")
        
        # Instagram URLs
        self.INSTAGRAM_URL = "https://www.instagram.com"
        self.PROFILE_URL = "https://www.instagram.com/ruby_genius/"
        
        # Track stats
        self.stats = {
            "followers": 0,
            "following": 0,
            "posts": 0,
            "engagement_rate": 0,
            "daily_growth": 0,
            "comments_received": 0,
            "likes_received": 0,
            "last_post_date": None,
            "best_performing_post": None,
            "follower_growth_rate": 0,
            "story_views": 0,
            "reel_views": 0,
            "dm_messages": 0,
            "collab_requests": 0
        }
        
        # Load existing data
        self._load_data()
        
        # Initialize auto scripts
        self._initialize_auto_scripts()
    
    def _load_data(self):
        """Load Instagram data from files"""
        # Load profile data
        if os.path.exists(self.profile_file):
            try:
                data = json.loads(self.file_tool.read_file(self.profile_file))
                self.stats.update(data)
                print(f"📸 Loaded Instagram profile data: {self.stats['followers']} followers")
            except:
                pass
        
        # Load Instagram memory
        if os.path.exists(self.instagram_memory_file):
            try:
                memory_data = json.loads(self.file_tool.read_file(self.instagram_memory_file))
                self.connected = memory_data.get("connected", False)
                self.last_sync = datetime.fromisoformat(memory_data["last_sync"]) if memory_data.get("last_sync") else None
                print(f"📸 Loaded Instagram memory: connected={self.connected}")
            except:
                pass
    
    def _save_data(self):
        """Save Instagram data to files"""
        # Save profile data
        self.file_tool.write_file(
            self.profile_file,
            json.dumps(self.stats, indent=2, default=str)
        )
        
        # Save Instagram memory
        memory_data = {
            "connected": self.connected,
            "last_sync": self.last_sync.isoformat() if self.last_sync else None,
            "stats": self.stats,
            "updated_at": datetime.now().isoformat()
        }
        self.file_tool.write_file(
            self.instagram_memory_file,
            json.dumps(memory_data, indent=2, default=str)
        )
    
    def _initialize_auto_scripts(self):
        """Create automated Instagram scripts"""
        auto_script = '''#!/usr/bin/env python3
"""
Ruby's Auto Instagram Script - Generated by Ruby herself
"""
import os
import sys
import json
import time
from datetime import datetime

def auto_post():
    """Automatically post content"""
    print("📸 Ruby is auto-posting...")
    # Add Instagram API posting logic here
    return True

def auto_respond():
    """Automatically respond to comments"""
    print("💬 Ruby is auto-responding...")
    # Add comment response logic here
    return True

def auto_analyze():
    """Automatically analyze engagement"""
    print("📊 Ruby is analyzing engagement...")
    # Add analytics logic here
    return True

def main():
    """Main auto script"""
    print(f"🤖 Ruby's Auto Instagram Script - {datetime.now()}")
    
    # Parse arguments
    if len(sys.argv) > 1:
        action = sys.argv[1]
        if action == "post":
            auto_post()
        elif action == "respond":
            auto_respond()
        elif action == "analyze":
            auto_analyze()
        else:
            print(f"Unknown action: {action}")
    else:
        # Run all actions
        auto_analyze()
        auto_respond()
        auto_post()

if __name__ == "__main__":
    main()
'''
        
        self.file_tool.write_file(self.auto_script_path, auto_script)
        os.chmod(self.auto_script_path, 0o755)  # Make executable
    
    def run_auto_post(self) -> dict:
        """Run auto-post script"""
        result = self.action_tool.run_python_script(self.auto_script_path)
        
        # Log result
        self.memory.save_hybrid_memory(
            f"Ruby auto-posted at {datetime.now().strftime('%H:%M')}",
            importance=2,
            category="instagram_automation"
        )
        
        return result
    
    def run_auto_respond(self) -> dict:
        """Run auto-response script"""
        result = self.action_tool.run_python_script(self.auto_script_path)
        
        self.memory.save_hybrid_memory(
            f"Ruby auto-responded to comments at {datetime.now().strftime('%H:%M')}",
            importance=2,
            category="instagram_automation"
        )
        
        return result
    
    def run_auto_analyze(self) -> dict:
        """Run auto-analysis script"""
        result = self.action_tool.run_python_script(self.auto_script_path)
        
        self.memory.save_hybrid_memory(
            f"Ruby auto-analyzed engagement at {datetime.now().strftime('%H:%M')}",
            importance=2,
            category="instagram_automation"
        )
        
        return result
    
    def run_backup(self) -> dict:
        """Run backup of Instagram data"""
        try:
            # Create backup directory
            backup_dir = os.path.join(self.data_dir, "backups")
            os.makedirs(backup_dir, exist_ok=True)
            
            # Create backup file
            backup_file = os.path.join(backup_dir, f"instagram_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json")
            
            # Gather all data
            backup_data = {
                "stats": self.stats,
                "learnings": self.get_learnings(),
                "content_ideas": self.get_content_ideas(),
                "comments": self.get_comments_from_file(),
                "connected": self.connected,
                "last_sync": self.last_sync.isoformat() if self.last_sync else None,
                "backup_time": datetime.now().isoformat()
            }
            
            # Write backup
            self.file_tool.write_file(
                backup_file,
                json.dumps(backup_data, indent=2, default=str)
            )
            
            # Save to memory
            self.memory.save_hybrid_memory(
                f"Instagram backup created: {os.path.basename(backup_file)}",
                importance=3,
                category="instagram_backup"
            )
            
            return {
                "success": True,
                "backup_file": backup_file,
                "message": f"Backup created successfully"
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "message": f"Backup failed: {e}"
            }
    
    def restore_backup(self, backup_file: str) -> dict:
        """Restore from backup"""
        try:
            if not os.path.exists(backup_file):
                return {"success": False, "message": "Backup file not found"}
            
            # Read backup data
            backup_data = json.loads(self.file_tool.read_file(backup_file))
            
            # Restore stats
            if "stats" in backup_data:
                self.stats.update(backup_data["stats"])
            
            # Restore learnings
            if "learnings" in backup_data:
                for learning in backup_data["learnings"]:
                    self.save_learning(learning["learning"], learning.get("importance", 2))
            
            # Restore content ideas
            if "content_ideas" in backup_data:
                for idea in backup_data["content_ideas"]:
                    self.save_content_idea(idea["idea"], idea.get("category", "post"))
            
            # Save restored data
            self._save_data()
            
            self.memory.save_hybrid_memory(
                f"Instagram restored from backup: {os.path.basename(backup_file)}",
                importance=3,
                category="instagram_restore"
            )
            
            return {
                "success": True,
                "message": f"Restored from backup successfully"
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "message": f"Restore failed: {e}"
            }
    
    def schedule_post(self, caption: str, image_path: str = None, scheduled_time: datetime = None) -> dict:
        """Schedule a post for later"""
        try:
            # Load existing scheduled posts
            posts = []
            if os.path.exists(self.scheduled_posts_file):
                try:
                    posts = json.loads(self.file_tool.read_file(self.scheduled_posts_file))
                except:
                    pass
            
            # Add new scheduled post
            scheduled_post = {
                "id": len(posts) + 1,
                "caption": caption,
                "image_path": image_path,
                "scheduled_time": (scheduled_time or datetime.now()).isoformat(),
                "status": "scheduled",
                "created_at": datetime.now().isoformat()
            }
            posts.append(scheduled_post)
            
            # Save back
            self.file_tool.write_file(
                self.scheduled_posts_file,
                json.dumps(posts, indent=2, default=str)
            )
            
            self.memory.save_hybrid_memory(
                f"Post scheduled: {caption[:50]}...",
                importance=2,
                category="instagram_scheduled"
            )
            
            return {
                "success": True,
                "message": f"Post scheduled for {scheduled_post['scheduled_time']}"
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "message": f"Schedule failed: {e}"
            }
    
    def get_scheduled_posts(self) -> List[Dict]:
        """Get all scheduled posts"""
        try:
            if os.path.exists(self.scheduled_posts_file):
                return json.loads(self.file_tool.read_file(self.scheduled_posts_file))
            return []
        except:
            return []
    
    def process_dm(self, message: str, username: str) -> str:
        """Process a DM from Instagram"""
        # Save DM
        self.memory.save_hybrid_memory(
            f"DM from {username}: {message[:50]}...",
            importance=3,
            category="instagram_dm"
        )
        
        # Generate response
        response = self._generate_dm_response(message, username)
        
        # Save response
        self.memory.save_hybrid_memory(
            f"Ruby replied to {username} in DM: {response[:50]}...",
            importance=2,
            category="instagram_dm"
        )
        
        return response
    
    def _generate_dm_response(self, message: str, username: str) -> str:
        """Generate response to DM"""
        message_lower = message.lower()
        
        if "collab" in message_lower or "collaboration" in message_lower:
            return f"OMG yes! I'd love to collab with you! 😱💕 What do you have in mind?"
        
        if "price" in message_lower or "sponsor" in message_lower:
            return f"Thank you for reaching out! I'm definitely interested! 💕 Tell me more about the opportunity!"
        
        if "fan" in message_lower or "love" in message_lower:
            return f"OMG thank you so much! 🥺 You're the sweetest! 💕"
        
        if "question" in message_lower or "?" in message:
            return f"Great question! 💭 Let me think about that... I'll get back to you!"
        
        return f"Hey! 💕 Thanks for reaching out! I'd love to chat more! What's on your mind?"
    
    def connect(self, username: str = None, password: str = None):
        """Connect Ruby to Instagram"""
        try:
            # Check if already logged in via browser profile
            result = self.browser.browse_social(
                self.INSTAGRAM_URL,
                action_type="read"
            )
            
            # Check if we got Instagram content
            if "instagram" in result.lower() or "login" not in result.lower():
                self.connected = True
                self.last_sync = datetime.now()
                
                # Store connection in memory and file
                connection_fact = f"Ruby connected to Instagram on {datetime.now().strftime('%B %d, %Y')}"
                self.memory.save_hybrid_memory(connection_fact, importance=3, category="instagram")
                
                # Save connection data
                self._save_data()
                print("📸 Ruby connected to Instagram!")
                return True
            
            return False
        except Exception as e:
            print(f"Instagram connection error: {e}")
            return False
    
    def get_profile_data(self):
        """Get Ruby's profile data from Instagram"""
        try:
            result = self.browser.browse_social(
                self.PROFILE_URL,
                action_type="read"
            )
            
            # Extract profile data
            if "followers" in result:
                import re
                # Extract followers count
                followers_match = re.search(r'(\d+[.,]?\d*)\s*(?:followers|Followers)', result)
                if followers_match:
                    self.stats["followers"] = int(followers_match.group(1).replace(',', '').replace('.', ''))
                
                # Extract posts count
                posts_match = re.search(r'(\d+[.,]?\d*)\s*(?:posts|Posts)', result)
                if posts_match:
                    self.stats["posts"] = int(posts_match.group(1).replace(',', ''))
            
            # Store in memory
            self.memory.save_hybrid_memory(
                f"Ruby's Instagram: {self.stats['followers']} followers, {self.stats['posts']} posts",
                importance=2,
                category="instagram_stats"
            )
            
            # Save to file
            self._save_data()
            
            return self.stats
        except Exception as e:
            print(f"Profile data error: {e}")
            return self.stats
    
    def save_comment_to_file(self, comment: str, username: str = "follower"):
        """Save Instagram comment to file for learning"""
        try:
            comments_data = []
            if os.path.exists(self.comments_file):
                try:
                    comments_data = json.loads(self.file_tool.read_file(self.comments_file))
                except:
                    pass
            
            comments_data.append({
                "username": username,
                "comment": comment,
                "timestamp": datetime.now().isoformat(),
                "processed": False
            })
            
            self.file_tool.write_file(
                self.comments_file,
                json.dumps(comments_data, indent=2, default=str)
            )
        except Exception as e:
            print(f"Save comment error: {e}")
    
    def get_comments_from_file(self, limit: int = 20) -> List[Dict]:
        """Get comments from file for learning"""
        try:
            if os.path.exists(self.comments_file):
                data = json.loads(self.file_tool.read_file(self.comments_file))
                return data[-limit:]
            return []
        except:
            return []
    
    def save_content_idea(self, idea: str, category: str = "post"):
        """Save content idea to file"""
        try:
            ideas_data = []
            if os.path.exists(self.content_ideas_file):
                try:
                    ideas_data = json.loads(self.file_tool.read_file(self.content_ideas_file))
                except:
                    pass
            
            ideas_data.append({
                "idea": idea,
                "category": category,
                "timestamp": datetime.now().isoformat(),
                "used": False
            })
            
            self.file_tool.write_file(
                self.content_ideas_file,
                json.dumps(ideas_data, indent=2, default=str)
            )
        except Exception as e:
            print(f"Save content idea error: {e}")
    
    def get_content_ideas(self, limit: int = 10) -> List[str]:
        """Get content ideas from file"""
        try:
            if os.path.exists(self.content_ideas_file):
                data = json.loads(self.file_tool.read_file(self.content_ideas_file))
                unused = [item for item in data if not item.get("used", False)]
                return [item["idea"] for item in unused[:limit]]
            return []
        except:
            return []
    
    def save_learning(self, learning: str, importance: int = 2):
        """Save a learning from Instagram"""
        try:
            learnings_data = []
            if os.path.exists(self.learnings_file):
                try:
                    learnings_data = json.loads(self.file_tool.read_file(self.learnings_file))
                except:
                    pass
            
            learnings_data.append({
                "learning": learning,
                "importance": importance,
                "timestamp": datetime.now().isoformat()
            })
            
            self.file_tool.write_file(
                self.learnings_file,
                json.dumps(learnings_data, indent=2, default=str)
            )
            
            self.memory.save_hybrid_memory(learning, importance=importance, category="instagram_learnings")
        except Exception as e:
            print(f"Save learning error: {e}")
    
    def get_learnings(self, limit: int = 10) -> List[str]:
        """Get learnings from file"""
        try:
            if os.path.exists(self.learnings_file):
                data = json.loads(self.file_tool.read_file(self.learnings_file))
                sorted_data = sorted(data, key=lambda x: (x.get("importance", 0), x["timestamp"]), reverse=True)
                return [item["learning"] for item in sorted_data[:limit]]
            return []
        except:
            return []
    
    def learn_from_instagram(self):
        """Main learning loop - what Ruby learns from Instagram"""
        self.get_profile_data()
        comments = self.get_comments_from_file()
        analysis = self.analyze_engagement()
        
        insights = []
        
        if analysis.get("engagement_rate", 0) > 50:
            insight = "Followers love Ruby's content! High positive engagement!"
            insights.append(insight)
            self.save_learning(insight, importance=3)
        
        if analysis.get("engagement_rate", 0) > 30:
            insight = "Good engagement! Keep posting what followers like."
            insights.append(insight)
            self.save_learning(insight, importance=2)
        
        if analysis.get("question_comments", 0) > 5:
            insight = "Followers ask lots of questions! Ruby should do a Q&A."
            insights.append(insight)
            self.save_learning(insight, importance=2)
        
        if analysis.get("collab_requests", 0) > 2:
            insight = "Collaboration requests coming in! Ruby should consider collabs."
            insights.append(insight)
            self.save_learning(insight, importance=3)
        
        if self.stats.get("followers", 0) > 1000:
            insight = f"Ruby hit {self.stats['followers']} followers! 🎉"
            insights.append(insight)
            self.save_learning(insight, importance=3)
        
        for insight in insights:
            if "Q&A" in insight:
                self.save_content_idea("Q&A session with followers!", "interactive")
            if "collab" in insight:
                self.save_content_idea("Collaboration post with another creator!", "collab")
        
        self._save_data()
        return insights
    
    def analyze_engagement(self) -> dict:
        """Analyze Instagram engagement patterns"""
        comments = self.get_comments_from_file()
        
        if not comments:
            return {"message": "No comments yet"}
        
        analysis = {
            "total_comments": len(comments),
            "positive_comments": 0,
            "question_comments": 0,
            "collab_requests": 0,
            "engagement_rate": 0
        }
        
        for item in comments:
            comment = item.get("comment", "").lower()
            if any(word in comment for word in ["love", "like", "cute", "pretty", "gorgeous"]):
                analysis["positive_comments"] += 1
            if "?" in comment:
                analysis["question_comments"] += 1
            if any(word in comment for word in ["collab", "collaboration", "together"]):
                analysis["collab_requests"] += 1
        
        if analysis["total_comments"] > 0:
            analysis["engagement_rate"] = (analysis["positive_comments"] / analysis["total_comments"]) * 100
        
        self.file_tool.write_file(
            os.path.join(self.data_dir, "analysis.json"),
            json.dumps(analysis, indent=2)
        )
        
        return analysis
    
    def generate_post_idea(self) -> str:
        """Generate post ideas from Instagram learnings and files"""
        saved_ideas = self.get_content_ideas()
        
        if saved_ideas:
            return random.choice(saved_ideas)
        
        ideas = [
            "Daily outfit vibe! What do you think? 💕",
            "Ruby's mood today: ✨💅 vibes only!",
            "POV: You caught Ruby in her natural element 📸",
            "What should Ruby post next? Drop your ideas! 💭",
            "Ruby's thought of the day: 💭 (tell me yours!)",
            "Behind the scenes of Ruby's day 📸✨",
            "Q&A time! Ask Ruby anything! 💕",
            "Ruby's fashion tips for the week! 💅"
        ]
        
        if self.stats.get("followers", 0) > 500:
            ideas.append("Thank you all for 500+ followers! 💕🎉")
        
        if self.stats.get("posts", 0) > 10:
            ideas.append("Ruby's 10th post celebration! 🎉")
        
        idea = random.choice(ideas)
        self.save_content_idea(idea)
        
        return idea
    
    def process_comment(self, comment: str, username: str = "follower") -> str:
        """Process a comment and generate Ruby's response"""
        self.save_comment_to_file(comment, username)
        response = self._generate_response(comment)
        self._learn_from_comment(comment, username)
        
        interaction = f"Ruby replied to {username}: {response[:50]}..."
        self.memory.save_hybrid_memory(interaction, importance=2, category="instagram_interactions")
        self.save_learning(interaction, importance=1)
        
        return response
    
    def _generate_response(self, comment: str) -> str:
        """Generate Ruby's natural response to comments"""
        comment_lower = comment.lower()
        
        responses = {
            "love": [
                "aww thank you! 💕 you're so sweet!",
                "omg thank you! 🥺 this made my day!",
                "sTOP you're making me blush! 😊💕",
                "thank you bestie! 💅✨"
            ],
            "question": [
                "great question! 💭 let me think about that...",
                "ooh good question! i'd say... 😏",
                "OMG i've been thinking about that too!",
                "interesting question! here's my take... 💕"
            ],
            "collab": [
                "collab?! 😱 let's do it! DM me! 💕",
                "omg yes! i'd love to collab with you! 🎉",
                "sTOP i was just thinking about collabing!",
                "definitely! let's make something amazing! ✨"
            ],
            "follow": [
                "welcome to the vibe! 💕✨",
                "thank you for following! you're the best! 🥺",
                "omg new follower?! hi! 💕",
                "welcome to Ruby's world! 🌎✨"
            ]
        }
        
        if any(word in comment_lower for word in ["love", "like", "cute", "pretty", "gorgeous"]):
            return random.choice(responses["love"])
        if "?" in comment_lower:
            return random.choice(responses["question"])
        if any(word in comment_lower for word in ["collab", "collaboration", "together"]):
            return random.choice(responses["collab"])
        if any(word in comment_lower for word in ["follow", "new follower"]):
            return random.choice(responses["follow"])
        
        default_responses = [
            "omg hey! 😊 thanks for the comment!",
            "hi! 💕 you're so sweet for commenting!",
            "i see you! 💅 thanks for showing up!",
            "you're the best! 🥺 appreciate you!",
            "omg i love your energy! 💕",
            "you're so nice! made my day! 🥺"
        ]
        return random.choice(default_responses)
    
    def _learn_from_comment(self, comment: str, username: str):
        """Learn from comment patterns"""
        comment_lower = comment.lower()
        
        if any(word in comment_lower for word in ["outfit", "style", "fashion", "look"]):
            learning = f"Followers are interested in fashion content from {username}"
            self.save_learning(learning, importance=3)
            self.memory.save_hybrid_memory(learning, importance=3, category="instagram_learning")
        
        if "?" in comment:
            question = comment.split("?")[0] + "?"
            learning = f"Common question on Instagram: {question}"
            self.save_learning(learning, importance=2)
            self.memory.save_hybrid_memory(learning, importance=2, category="instagram_questions")
        
        if any(word in comment_lower for word in ["collab", "collaboration"]):
            learning = f"@{username} is interested in collaborating!"
            self.save_learning(learning, importance=3)
            self.memory.save_hybrid_memory(learning, importance=3, category="instagram_collabs")
    
    def export_instagram_data(self) -> str:
        """Export all Instagram data to a single file"""
        export_data = {
            "stats": self.stats,
            "learnings": self.get_learnings(),
            "content_ideas": self.get_content_ideas(),
            "scheduled_posts": self.get_scheduled_posts(),
            "connected": self.connected,
            "last_sync": self.last_sync.isoformat() if self.last_sync else None,
            "exported_at": datetime.now().isoformat()
        }
        
        export_file = os.path.join(self.data_dir, f"instagram_export_{datetime.now().strftime('%Y%m%d')}.json")
        self.file_tool.write_file(
            export_file,
            json.dumps(export_data, indent=2, default=str)
        )
        
        return export_file
    
    def sync_data(self):
        """Sync all Instagram data to local memory and files"""
        self.last_sync = datetime.now()
        self.get_profile_data()
        insights = self.learn_from_instagram()
        
        sync_fact = f"Instagram sync at {self.last_sync.strftime('%H:%M')} - {self.stats['followers']} followers"
        self.memory.save_hybrid_memory(sync_fact, importance=1, category="instagram_sync")
        self.save_learning(sync_fact, importance=1)
        
        self.export_instagram_data()
        self._save_data()
        
        print(f"📸 Instagram synced! Followers: {self.stats['followers']}")
        return self.stats
